#! /bin/bash

# . ~morye/.config/colors/vs-code-style.conf
# . ~morye/.config/colors/pink-style.conf
. ~morye/.config/colors/colors.conf

# 
# Second monitor
#   consider setting workspaces 11-15 to the second monitor.
#   Switch between them with alternative key bindings like "super + alt + {1,5}"
# 

# if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
#     xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1
#     bspc monitor HDMI-1 -d 6 7 8 9 10
# fi


# auto start
setxkbmap us &
if pgrep -x "sxhkd"; then # manage sxhkd
    pkill -x sxhkd; sxhkd &
else
    sxhkd &
fi
bspc config -m focused bottom_padding $((`bspc config -m focused bottom_padding 0` )) # manage bspwm padding
bspc config -m focused top_padding $((`bspc config -m focused top_padding 0` ))
if pgrep -x "polybar"; then # manage polybar
    pkill polybar && polybar main &
else
    polybar main &
fi
if pgrep -x "flameshot"; then # manage flameshot
    pkill -x flameshot && flameshot &
else
    flameshot &
fi

xsetroot -cursor_name left_ptr &
# feh --bg-fill Images/wallpaper1.png
# feh --bg-fill Images/Anime/wallpaper-anime-3.jpg
feh --bg-fill $wallpaper

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# borders and gaps
bspc config border_width 1
bspc config window_gap 2

bspc config normal_border_color $color_black
bspc config active_border_color $color_green
bspc config focused_border_color $color_green

# color of section while creating new window
# bspc config presel_feedback_color "#fd2e59"
# bspc config presel_feedback_color "#0065a9"
bspc config presel_feedback_color $color_green

# separation coeficient
bspc config split_ratio 0.5

# window focus by cursor pointing
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# monocle mode, when one window is opened
bspc config single_monocle false
bspc config gapless_monocle false
bspc config borderless_monocle true


#
# TODO: window rules
#
